spring.application.name=weathertrip-backend
# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/weathertripdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:changeme}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

geoapify.api.key=${GEOAPIFY_API_KEY:}


# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080
